import { existsSync, readFileSync } from "fs";
import * as path from "path";

type CatalogJson = { byIndustry?: Record<string, string[]> };

/** Reads `signup-org-catalog.json` generated by `scripts/build-signup-org-catalog.mjs`. */
export function readBundledSignupByIndustry(): Record<string, string[]> {
  const candidates = [
    path.join(process.cwd(), "signup-org-catalog.json"),
    path.join(process.cwd(), "dist", "signup-org-catalog.json"),
  ];
  for (const filePath of candidates) {
    try {
      if (!existsSync(filePath)) continue;
      const parsed = JSON.parse(readFileSync(filePath, "utf8")) as CatalogJson;
      if (parsed?.byIndustry && typeof parsed.byIndustry === "object") return parsed.byIndustry;
    } catch {
      /* ignore */
    }
  }
  return {};
}

export function mergeIndustryDeptIntoMap(target: Map<string, Set<string>>, source: Record<string, string[]>) {
  for (const [ind, arr] of Object.entries(source)) {
    const iname = String(ind || "").trim();
    if (!iname || !Array.isArray(arr)) continue;
    if (!target.has(iname)) target.set(iname, new Set());
    const set = target.get(iname)!;
    for (const d of arr) {
      const dd = String(d || "").trim();
      if (dd) set.add(dd);
    }
  }
}
